name: Deploy to VPS

on:
    push:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Push to Dokku
              uses: https://github.com/dokku/github-action@master
              with:
                  git_remote_url: ${{ secrets.GIT_REMOTE_URL }}
                  ssh_private_key: ${{ secrets.PRIVATE_KEY }}
